spring:
  datasource:
    url: jdbc:postgresql://${IDENTITY_DB_HOST:localhost}:${IDENTITY_DB_PORT:5432}/${IDENTITY_DB_NAME:identity_db}
    username: ${IDENTITY_DB_USER:orion_identity}
    password: ${IDENTITY_DB_PASSWORD:identity_secret}
  flyway:
    url: jdbc:postgresql://${IDENTITY_DB_HOST:localhost}:${IDENTITY_DB_PORT:5432}/${IDENTITY_DB_NAME:identity_db}
    user: ${IDENTITY_DB_USER:orion_identity}
    password: ${IDENTITY_DB_PASSWORD:identity_secret}
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
