version: '3.8'

services:
  notifications-service:
    build: .
    container_name: notifications-service
    ports:
      - "8081:8081" # Assuming a different port for notifications service
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orionticket_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    # Link to the shared network defined in the root docker-compose.yml
    networks:
      - orionticket_network

networks:
  orionticket_network:
    external: true
    name: orionticket_default
