spring:
  application:
    name: event-management-service
  datasource:
    url: jdbc:postgresql://${EVENT_MANAGEMENT_DB_HOST:localhost}:${EVENT_MANAGEMENT_DB_PORT:5432}/${EVENT_MANAGEMENT_DB_NAME:event_management_db}
    username: ${EVENT_MANAGEMENT_DB_USER:orion}
    password: ${EVENT_MANAGEMENT_DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: ${SERVER_PORT:8082}
